Squashed feature handle error 2 (#1527)
* Add @glimmer/debug as a runtime dep for @glimmer/runtime

Not 100% sure if this is intentional or unintentional leakage, but
the imports made its way to the `dist` output.

* Use relative imports for package-self-reference

AFAIK this is supposed to work, but TypeScript appears to be having
issues with it on the Ember side:

```
../glimmer-vm/dist/@glimmer/interfaces/lib/references.d.ts:1:38 - error TS2307: Cannot find module '@glimmer/interfaces' or its corresponding type declarations.

1 import type { DevMode, Result } from '@glimmer/interfaces';
                                       ~~~~~~~~~~~~~~~~~~~~~

../glimmer-vm/dist/@glimmer/interfaces/lib/runtime/debug-vm.d.ts:12:8 - error TS2307: Cannot find module '@glimmer/interfaces' or its corresponding type declarations.

12 } from '@glimmer/interfaces';
          ~~~~~~~~~~~~~~~~~~~~~
```

It is possible that the more correct fix is to update some setting
in the Ember tsconfig (`"moduleResolution": "bundler"`?) but this
sidesteps the issue for now.

* Use a single version of vite

* Don't reference tsconfig that doesn't exist

* lint:fix

* Allow any Vite version, because there are tools in @glimmer-workspace that are out of date / chose the wrong peer range sigil

* lintfix

---------

Co-authored-by: NullVoxPopuli <199018+NullVoxPopuli@users.noreply.github.com>